name: pacpac
channels:
  - defaults
  - bioconda
dependencies:
  - anarci=2021.02.04
  - numpy==1.18.5
  - pip=21
  - python=3.7
  - pip:
    - numba==0.54
    - pandas==1.1.5
    - tensorflow==1.15.5
    - keras==2.2.4
    - h5py==2.10.0
    - pandarallel==1.5.2
    - pyfiglet==0.8.post1
    - typer==0.3.2
