name: pacpac
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - anarci=2020.04.23=py_3
  - docopt=0.6.2=py36_0
  - h5py=2.10.0
  - numpy=1.19.2
  - pandas=0.23.4
  - pip=20.2.4=py36_0
  - python=3.6.12
  - tensorflow=1.2.1=py36_0
  - pip:
    - keras==2.0.6
    - pandarallel==1.5.1
    - pyfiglet==0.8.post1
