name: ci

on:
  push:
    branches: [main] 
  pull_request:
    branches: [main]  
  schedule:
  - cron: "0 0 27 * *"

jobs:
  build-linux:
  
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
    - name: create conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        installer-url: https://repo.anaconda.com/miniconda/Miniconda3-py37_22.11.1-1-Linux-x86_64.sh
        auto-activate-base: false
        environment-file: environment.yml
        activate-environment: pacpac
    - name: install package
      run: pip install .
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      working-directory: ./tests
      run: |
        pip install pytest
        pytest

  build-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pacpac:latest

